# Generated by Django 3.0.7 on 2020-07-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200625_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('desc', models.CharField(max_length=500)),
                ('state', models.CharField(default='', max_length=50)),
                ('pin', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
